### ISSUE TITLE
Add .Net Standard Support

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-relay-dotnet#5]
Adding this issue to track .NET Standard / Core support. We plan to have this by general availability.

**Comment by dstuckims** [comment]
The biggest issue that needs to be address is the ClientWebSocket[45] class.  We had to clone the framework's ClientWebSocket class in order to get the listener accept commands to be able to use an IP address but validate the SSL cert is actually *.servicebus.windows.net.  The .NET Reference Source version of ClientWebSocket is different from the .NET Core version so similar, yet different, work needs to be done to get this to work with .NET Core.

**Comment by jtaubensee** [comment]
Closing per #21
