### ISSUE TITLE
HybridConnectionListener memory leak?

### ISSUE THREAD

**Issue by YARG** [Azure/azure-relay-dotnet#83]
## Actual Behavior
1.  In VS 2017 run server example from 
https://github.com/Azure/azure-relay/tree/master/samples/hybrid-connections/dotnet/simple-http/Server

2. Open up VS memory profile
3. Make client request #1, memory foot print increases (as expected)
4. Make client request #2, memory foot print increases some of which gets reclaimed
5. Make 10/15 client requests in succession, waiting for the response on each, and memory increases even further and doesn't seem to get reclaimed.

![mem_leak2](https://user-images.githubusercontent.com/568435/47996139-6ddff700-e0ef-11e8-951a-be3a51a69079.PNG)

## Expected Behavior
After the initial and further requests more memory should be reclaimed/freed.

I'm running the example on a Windows 7 box with .NET Core 2.1.5 installed.

FYI I'm running my own implementation on a Windows Server 2008 R2 (.NET Core 2.1.5) 
and based on similar tests memory still hasn't been reclaimed after a few days of operation.  
## Versions  
- OS platform and version:
Windows 7 Enterprise SP1 64bit
- .NET Version:
.NET Core 2.1.5
- NuGet package version or commit ID:
Microsoft.Azure.Relay v2.0.0-preview1-20180523

**Comment by dlstucki** [comment]
Are you seeing OutOfMemoryExceptions being thrown?

**Comment by dlstucki** [comment]
The .NET Garbage Collector does not work quite how you describe in your **Expected Behavior**.

Consider this example application:
``` C#
class Program
{
    static void Main(string[] args)
    {
        bool keepGoing = true;
        while (keepGoing)
        {
            Console.WriteLine("Enter a command:");
            Console.WriteLine("a10\tAllocate 10MB");
            Console.WriteLine("a100\tAllocate 100MB");
            Console.WriteLine("g\tRun GC.Collect");
            Console.WriteLine("q\tQuit");
            Console.Write("> ");
            string line = Console.ReadLine();
            switch (line.ToLowerInvariant())
            {
                case "a10":
                    Allocate(10);
                    break;
                case "a100":
                    Allocate(100);
                    break;
                case "g":
                    GC.Collect();
                    break;
                case "q":
                    keepGoing = false;
                    break;
                default:
                    Console.WriteLine($"Unknown command '{line}'");
                    break;
            }
        }
    }

    static void Allocate(int megabytesToAllocate)
    {
        var arrays = new List<byte[]>();
        long totalBytesAllocated = 0;
        for (int j = 0; j < megabytesToAllocate * 1024; j++)
        {
            var data = new byte[1024];
            totalBytesAllocated += data.Length;
            arrays.Add(data);
            Thread.Sleep(0);
        }
    }
}
```

**Scenario A**
1. Start and wait 5 seconds
2. Allocate 100MB ('a100' command)
3. Wait 60 seconds
4. Call GC.Collect ('g' command)
![image](https://user-images.githubusercontent.com/11354387/48020193-25720a80-e0ea-11e8-8808-eb12b128b6e0.png)

After allocating 100MB, even though it's not longer rooted, if no other allocations take place, then the 100MB will not be collected. Waiting for a day or two won't make any difference.

**Scenario B**
1. Start and wait 5 seconds
2. Allocate 100MB ('a100' command), wait 15 seconds
3. Allocate 10MB ('a10' command) every 5 seconds
![image](https://user-images.githubusercontent.com/11354387/48020396-aa5d2400-e0ea-11e8-8d19-b8fbc0893b5e.png)

Notice that after about the 10th time executing step 3. that finally the GC cleaned up the 100MB.

**Comment by YARG** [comment]
dlstucki, thanks for this and yes you’re correct, in the code example and my tests GC hadn’t kicked in (no OutOfMemory raised either).  I just saw the memory rise when in the past when I worked on an Azure Service Bus WCF Relay implementation the memory reclaimed was quicker without GC kicking in.

Making an explicit call to GC.Collect() (only as a test) does eventually reclaim, so I’ll close this, sorry for wasting your time .. I need to be more patient!  Thanks again for the quick response and the great GC Examples.
